services:
  - type: web
    name: ciclo-datos-salud
    runtime: static
    buildCommand: echo "Sitio estatico, sin compilacion"
    staticPublishPath: .
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: "true"
